name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^2.0.1
  flutter_clock_helper:
    path: ../flutter_clock_helper
  mechanical_clock:
    path: ../mechanical_clock

  
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Baloo
      fonts:
        - asset: third_party/Baloo-Regular.ttf
  assets:
    - daily.flr
